# Credit Risk Resampling Techniques

In [40]:
import warnings
warnings.filterwarnings('ignore')
!pip3 install scikit-learn==1.0 -U

Requirement already satisfied: scikit-learn==1.0 in /usr/local/lib/python3.7/dist-packages (1.0)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==1.0) (1.19.5)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==1.0) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==1.0) (3.0.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==1.0) (1.4.1)

In [41]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV and Perform Basic Data Cleaning

In [42]:
columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [14]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

   loan_amnt  int_rate  ...  hardship_flag debt_settlement_flag
0    10500.0    0.1719  ...              N                    N
1    25000.0    0.2000  ...              N                    N
2    20000.0    0.2000  ...              N                    N
3    10000.0    0.1640  ...              N                    N
4    22000.0    0.1474  ...              N                    N

[5 rows x 86 columns]

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Split the Data into Training and Testing

In [16]:
# Create our features
X = pd.get_dummies(df, columns=["home_ownership","verification_status", "issue_d", "pymnt_plan","initial_list_status","next_pymnt_d", "application_type","hardship_flag", "debt_settlement_flag"])
X = X.drop(["loan_status"], axis=1)

# Create our target
y = df["loan_status"]

In [17]:
X.describe()

          loan_amnt      int_rate  ...  hardship_flag_N  debt_settlement_flag_N
count  68817.000000  68817.000000  ...          68817.0                 68817.0
mean   16677.594562      0.127718  ...              1.0                     1.0
std    10277.348590      0.048130  ...              0.0                     0.0
min     1000.000000      0.060000  ...              1.0                     1.0
25%     9000.000000      0.088100  ...              1.0                     1.0
50%    15000.000000      0.118000  ...              1.0                     1.0
75%    24000.000000      0.155700  ...              1.0                     1.0
max    40000.000000      0.308400  ...              1.0                     1.0

[8 rows x 95 columns]

In [18]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=28)
Counter(y_train)

Counter({'high_risk': 273, 'low_risk': 51339})

# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [20]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=28)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

Counter(y_resampled)

Counter({'high_risk': 51339, 'low_risk': 51339})

In [21]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=28)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=28)

In [22]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score

y_pred = model.predict(X_test)
acc_score = balanced_accuracy_score(y_test, y_pred)

In [23]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

# Create df for confusion matrix
cm_df = pd.DataFrame(
    cm, index=["Actual High Risk", "Actual Low Risk"], columns=["Predicted High Risk", "Predicted Low Risk"])

cm_df

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   49                  25
Actual Low Risk                  5339               11792

In [24]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

# Displaying results
print("Oversampling Analysis")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

Oversampling Analysis
Confusion Matrix

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   49                  25
Actual Low Risk                  5339               11792

Accuracy Score : 0.6752524662891833
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.66      0.69      0.02      0.68      0.45        74
   low_risk       1.00      0.69      0.66      0.81      0.68      0.46     17131

avg / total       0.99      0.69      0.66      0.81      0.68      0.46     17205

### SMOTE Oversampling

In [25]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=28, sampling_strategy='auto').fit_resample(
    X_train, y_train
)
Counter(y_resampled)

Counter({'high_risk': 51339, 'low_risk': 51339})

In [26]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=28)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=28)

In [27]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
acc_score = balanced_accuracy_score(y_test, y_pred)

In [28]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Create df for confusion matrix
cm_df = pd.DataFrame(
    cm, index=["Actual High Risk", "Actual Low Risk"], columns=["Predicted High Risk", "Predicted Low Risk"])

cm_df

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   52                  22
Actual Low Risk                  5970               11161

In [29]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

# Displaying results
print("SMOTE Analysis")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

SMOTE Analysis
Confusion Matrix

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   52                  22
Actual Low Risk                  5970               11161

Accuracy Score : 0.6771058315334774
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.70      0.65      0.02      0.68      0.46        74
   low_risk       1.00      0.65      0.70      0.79      0.68      0.46     17131

avg / total       0.99      0.65      0.70      0.79      0.68      0.46     17205

# Undersampling

In this section, you will test an undersampling algorithms to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [30]:
# Resample the data using the ClusterCentroids resampler
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=28)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'high_risk': 273, 'low_risk': 273})

In [31]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=28)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=28)

In [32]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
acc_score = balanced_accuracy_score(y_test, y_pred)

In [33]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Create df for confusion matrix
cm_df = pd.DataFrame(
    cm, index=["Actual High Risk", "Actual Low Risk"], columns=["Predicted High Risk", "Predicted Low Risk"])

cm_df

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   47                  27
Actual Low Risk                 10215                6916

In [34]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

# Displaying results
print("Undersampling Analysis")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

Undersampling Analysis
Confusion Matrix

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   47                  27
Actual Low Risk                 10215                6916

Accuracy Score : 0.5194238514972855
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.00      0.64      0.40      0.01      0.51      0.26        74
   low_risk       1.00      0.40      0.64      0.57      0.51      0.25     17131

avg / total       0.99      0.40      0.63      0.57      0.51      0.25     17205

# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [35]:
# Resample the training data with SMOTEENN
from imblearn.combine import SMOTEENN

smote_enn = SMOTEENN(random_state=28)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)
Counter(y_resampled)

Counter({'high_risk': 68461, 'low_risk': 62033})

In [36]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=28)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=28)

In [37]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
acc_score = balanced_accuracy_score(y_test, y_pred)

In [38]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Create df for confusion matrix
cm_df = pd.DataFrame(
    cm, index=["Actual High Risk", "Actual Low Risk"], columns=["Predicted High Risk", "Predicted Low Risk"])

cm_df

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   56                  18
Actual Low Risk                  6775               10356

In [39]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

# Displaying results
print("SMOTEENN Analysis")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

SMOTEENN Analysis
Confusion Matrix

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   56                  18
Actual Low Risk                  6775               10356

Accuracy Score : 0.6806374408966203
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.76      0.60      0.02      0.68      0.46        74
   low_risk       1.00      0.60      0.76      0.75      0.68      0.45     17131

avg / total       0.99      0.61      0.76      0.75      0.68      0.45     17205